### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by stefdoerr** [conda-forge/moleculekit-feedstock#62]
### Comment:

Well, not much to say here other than thanks for doing this! 
I have wanted for a long while to move moleculekit to conda-forge but never figured out how, so many many thanks :)

**Comment by jan-janssen** [comment]
If you are interested, I am happy to add you as a maintainer.

**Comment by stefdoerr** [comment]
There is a significant issue I just noticed though which is the license. The license of moleculekit is not BSD, we use a custom license

https://github.com/Acellera/moleculekit/blob/main/LICENSE

And yes please add me as maintainer as the distribution needs to be controlled by Acellera

**Comment by jan-janssen** [comment]
@conda-forge-admin, please add user @stefdoerr
